[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/hariank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.mainnet]
sol_cron = "A4f4ZDWEPLXnY8jGhTY5JfZZG6CTRBi5ikgtpQ2pbv8g"

[programs.devnet]
sol_cron = "A4f4ZDWEPLXnY8jGhTY5JfZZG6CTRBi5ikgtpQ2pbv8g"

[programs.testnet]
sol_cron = "A4f4ZDWEPLXnY8jGhTY5JfZZG6CTRBi5ikgtpQ2pbv8g"

[programs.localnet]
sol_cron = "A4f4ZDWEPLXnY8jGhTY5JfZZG6CTRBi5ikgtpQ2pbv8g"
